### ISSUE TITLE
Swapping image set

### ISSUE THREAD

**Issue by andy008** [andrepolischuk/circlr#13]
I have multiple 24 frame sequences I need to switch between. Running with a single view in Ionic.

To swap image sets, I simply swap the IMG urls in the model.  To set the new image set to spin once, have tried to unbind and reapply circlr, or to use play, but this seems to result in two instances of Circlr (noticeable by the BLOCK style being applied to two different images).

Is this a bug or a problem with my implementation?

**Comment by andrepolischuk** [comment]
I have try this but with pure js:

```js
let rotation

function createRotation(startIndex) {
  const container = document.querySelector('.rotation')

  if (rotation) {
    rotation.unbind()
    container.innerHTML = ''
  }

  for (var i = startIndex; i < startIndex + 5; i++) {
    const image = new Image()
    image.src = `images/${i < 10 ? '0' : ''}${i}.jpg`
    container.appendChild(image)
  }

  rotation = circlr('.rotation')
}

// createRotation(0)
// createRotation(5)
// createRotation(10)
```

and all is working correctly.

@andy008 can you show you code example?

**Comment by andrepolischuk** [comment]
You can try call `.stop()` before `unbind`:

```js
let rotation = circlr(el).play()
// ...
rotation.stop().unbind()
// ...update image nodes
rotation = circlr(el).play()
```

**Comment by andrepolischuk** [comment]
I close this. Write to me if you still have questions.
