### ISSUE TITLE
Fix image flicker effect

### ISSUE THREAD

**Issue by julmot** [andrepolischuk/circlr#14]
This plugin seems to be simple and easy in comparison to others. However, I can't use it as it has one significant disadvantage: Images aren't preloaded. This causes a flicker effect that is very ugly:

![circlr](https://user-images.githubusercontent.com/8310677/28365905-ba1128c2-6c8a-11e7-9f7a-63bc08900ff2.gif)

**Comment by andrepolischuk** [comment]
I think circlr not about deffered loading, and developers should handle loading himself. For example you can preload all images in set and call circle constructor after that.

**Comment by julmot** [comment]
I don't agree with you, this is something all other plugins are covering and that's the reason why I will use them instead of circlr. Think like a developer – why should someone choose a plugin with more integration effort when there are other solutions out there solving it without that effort?

**Comment by andrepolischuk** [comment]
> This plugin seems to be simple and easy in comparison to others

Module will not be a simple If I will introduce all requests.

> Think like a developer – why should someone choose a plugin with more integration effort

I dont know which way any developer will choose for image preloading. What about usage <svg /> tag as elements or <div /> with `background-image`?
