### ISSUE TITLE
dragging functionality in IE10+

### ISSUE THREAD

**Issue by python3k** [andrepolischuk/circlr#8]
Just to let you know that Circlr dragging functionality works on IE9, but not on IE10+ anymore.

**Comment by andrepolischuk** [comment]
I have tested [demo page](http://andrepolischuk.github.io/circlr/) in IE10 and can't reproduce this. Can you attach your code example where circlr is not working.

**Comment by python3k** [comment]
Thank you for your quick response.
I have based myself on the following page, which is not mine:
http://www.cssscript.com/demo/360-degree-image-viewer-with-pure-javascript-circlr/

When i open this in IE and set the emulation to IE10+ then i am unable to drag the image horizontally.

**Comment by andrepolischuk** [comment]
This example is built on the outdated circlr version.
This IE10+ bug is fixed in current version ^2.0.3.

**Comment by python3k** [comment]
thanks. i will look into this.

I see that you are using require.js (index.js) and also the dependencies emitter, events, and wheel.
Is it possible to use circlr without requireJS?

**Comment by andrepolischuk** [comment]
You can generate [UMD](https://github.com/forbeslindesay/umd) bundle with [browserify](http://browserify.org/). Or you can use [this bundle](https://gist.github.com/andrepolischuk/2de87e2a3c4d05c458e2).

**Comment by python3k** [comment]
Thank you for your help.

It does seem to work now on IE10+, and Chrome as well, 
even though it doesn't load properly on Firefox.
Perhaps i am doing something wrong here. I will try to figure it out later.

By the way, is it possible that the API has changed:
- constructor now requires a css class ('.circlr') instead of just a name ('circlr')
- go(i) has been replaced by show(i)

**Comment by andrepolischuk** [comment]
API was changed starting from 2.0.0 version
